package com.drafthj.mapper;

import com.drafthj.model.StudentCourse;
import com.drafthj.model.StudentCourseExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.Update;

public interface StudentCourseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_course
     *
     * @mbggenerated Thu Mar 17 13:37:34 CST 2016
     */
    int countByExample(StudentCourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_course
     *
     * @mbggenerated Thu Mar 17 13:37:34 CST 2016
     */
    int deleteByExample(StudentCourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_course
     *
     * @mbggenerated Thu Mar 17 13:37:34 CST 2016
     */
    @Delete({
        "delete from student_course",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_course
     *
     * @mbggenerated Thu Mar 17 13:37:34 CST 2016
     */
    @Insert({
        "insert into student_course (id, student_id, ",
        "course_id, score)",
        "values (#{id,jdbcType=INTEGER}, #{studentId,jdbcType=INTEGER}, ",
        "#{courseId,jdbcType=INTEGER}, #{score,jdbcType=DOUBLE})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=true, resultType=Integer.class)
    int insert(StudentCourse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_course
     *
     * @mbggenerated Thu Mar 17 13:37:34 CST 2016
     */
    int insertSelective(StudentCourse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_course
     *
     * @mbggenerated Thu Mar 17 13:37:34 CST 2016
     */
    List<StudentCourse> selectByExample(StudentCourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_course
     *
     * @mbggenerated Thu Mar 17 13:37:34 CST 2016
     */
    @Select({
        "select",
        "id, student_id, course_id, score",
        "from student_course",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("BaseResultMap")
    StudentCourse selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_course
     *
     * @mbggenerated Thu Mar 17 13:37:34 CST 2016
     */
    int updateByExampleSelective(@Param("record") StudentCourse record, @Param("example") StudentCourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_course
     *
     * @mbggenerated Thu Mar 17 13:37:34 CST 2016
     */
    int updateByExample(@Param("record") StudentCourse record, @Param("example") StudentCourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_course
     *
     * @mbggenerated Thu Mar 17 13:37:34 CST 2016
     */
    int updateByPrimaryKeySelective(StudentCourse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_course
     *
     * @mbggenerated Thu Mar 17 13:37:34 CST 2016
     */
    @Update({
        "update student_course",
        "set student_id = #{studentId,jdbcType=INTEGER},",
          "course_id = #{courseId,jdbcType=INTEGER},",
          "score = #{score,jdbcType=DOUBLE}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(StudentCourse record);
}