package com.drafthj.model;

public class StudentCourse {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_course.id
     *
     * @mbggenerated Thu Mar 17 13:37:34 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_course.student_id
     *
     * @mbggenerated Thu Mar 17 13:37:34 CST 2016
     */
    private Integer studentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_course.course_id
     *
     * @mbggenerated Thu Mar 17 13:37:34 CST 2016
     */
    private Integer courseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_course.score
     *
     * @mbggenerated Thu Mar 17 13:37:34 CST 2016
     */
    private Double score;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_course
     *
     * @mbggenerated Thu Mar 17 13:37:34 CST 2016
     */
    public StudentCourse(Integer id, Integer studentId, Integer courseId, Double score) {
        this.id = id;
        this.studentId = studentId;
        this.courseId = courseId;
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_course
     *
     * @mbggenerated Thu Mar 17 13:37:34 CST 2016
     */
    public StudentCourse() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_course.id
     *
     * @return the value of student_course.id
     *
     * @mbggenerated Thu Mar 17 13:37:34 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_course.id
     *
     * @param id the value for student_course.id
     *
     * @mbggenerated Thu Mar 17 13:37:34 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_course.student_id
     *
     * @return the value of student_course.student_id
     *
     * @mbggenerated Thu Mar 17 13:37:34 CST 2016
     */
    public Integer getStudentId() {
        return studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_course.student_id
     *
     * @param studentId the value for student_course.student_id
     *
     * @mbggenerated Thu Mar 17 13:37:34 CST 2016
     */
    public void setStudentId(Integer studentId) {
        this.studentId = studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_course.course_id
     *
     * @return the value of student_course.course_id
     *
     * @mbggenerated Thu Mar 17 13:37:34 CST 2016
     */
    public Integer getCourseId() {
        return courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_course.course_id
     *
     * @param courseId the value for student_course.course_id
     *
     * @mbggenerated Thu Mar 17 13:37:34 CST 2016
     */
    public void setCourseId(Integer courseId) {
        this.courseId = courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_course.score
     *
     * @return the value of student_course.score
     *
     * @mbggenerated Thu Mar 17 13:37:34 CST 2016
     */
    public Double getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_course.score
     *
     * @param score the value for student_course.score
     *
     * @mbggenerated Thu Mar 17 13:37:34 CST 2016
     */
    public void setScore(Double score) {
        this.score = score;
    }
}